
include ../../common.mak

LDFLAGS =  $(LIBDOMINO) $(LIBDO) $(LIBEXPAT) -g -O1

SRCS =load.c date_util.c read_files.c
SRCS_1 = unload.c

APP = lilly-load
APP_1 = lilly-upload


include ../../program.mak


