
include ../../common.mak

LDFLAGS = `pkg-config python-2.7 --libs` 
CFLAGS = -D_REENTRANT `pkg-config python-2.7 --cflags` 

SRCS = sad.c

VER = 1
NAME = sad.so
DLL  = testp.dll

include ../../library.mak


