#!/bin/sh

if [ -f /etc/init.d/dclubd ] ; then
/etc/init.d/dclubd stop
rm /etc/init.d/dclubd
fi
if [ -f /etc/init.d/exchanged ] ; then
/etc/init.d/exchanged stop
rm /etc/init.d/exchanged
fi
if [ -f /etc/init.d/get-video ] ; then
/etc/init.d/get-video stop
fi
exit 0