
include ../../common.mak

LDFLAGS =  $(LIBGTK) $(LIBSPREADSHEET) $(WINAPP) $(LIBICONV)


SRCS = main.c do_progress_info.c do_report_plugin.c do_scan.c

APP = gnumeric-report-plugin

include ../../program.mak


