#!/bin/sh
#

if [ $1 -lt 10 ] ; then
    SFUNIT="СФ0$1"
else
    SFUNIT="СФ$1"
fi
DOCS="ПТ.$1,F1.$SFUNIT,РТ.$1,PR.$1,ИО.$1,ИТ.$1,ИП.$1"


/usr/local/domino/bin/sync-client$1 parcels $1 stocks $1 document_period $DOCS yesterday-2 yesterday document_modified $DOCS yesterday today  protocol yesterday yesterday checks $1 yesterday-2 yesterday  
#>>/usr/local/domino/log/sync-client$1.log
