
include ../../common.mak

LDFLAGS =  $(LIBDOMINO) $(LIBDO)
CFLAGS = -DNOCORRECTNDS

SRCS = doc_print.c ../../misc/forms.c ../../misc/template.c ../../misc/print.c 
#SRCS_1 = post.c

APP = doc_print
#APP_1 = postperiod


include ../../program.mak


