
include ../../common.mak

LDFLAGS =  $(LIBDO)  $(LIBLOUDMOUTH) $(LIBGLIB) $(LIBWINSOCK) $(LIBICONV)
CFLAGS =  $(GLIBCFLAGS) -DGLOG_OFF -DUSE_IM

SRCS = main.c 

APP = sad

include ../../program.mak


