
include ../../common.mak

LDFLAGS = $(LIBGTK) $(LIBPQ) 

CFLAGS = $(GTKCFLAGS) $(PQCFLAGS)

SRCS = dopricewidget.c dosettings.c dotreeview.c dowindow.c main.c ../../misc/gtktreecelldatafunc.c

APP = price

include ../../program.mak
