
include ../../common.mak

LDFLAGS = $(LIBPTHEAD) $(LIBZ) $(LIBICONV) $(LIBWINSOCK)
CFLAGS = -D_REENTRANT -DDEBUG1

SRCS = log.c auth.c list.c mem.c data.c socket_io.c rpc_client.c rpc.c scanner.c thread.c \
	proc_state.c service.c util.c $(misc)/iconv_.c charset.c numutils.c ole.c xls.c

VER = 1
NAME = dolib.dll

include ../../library.mak


