
include ../../common.mak

LDFLAGS =  $(LIBDOMINO) $(LIBDO) $(LIBEXPAT)

SRCS =load.c date_util.c read_files.c
SRCS_1 = unload.c

APP = pfizer-load
APP_1 = pfizer-upload


include ../../program.mak


